### ISSUE TITLE
2023-04-30-wstring_convert.md

### ISSUE THREAD

**Issue by longlongvip** [Jackarain/jackarain.github.com#1]
搞笑，utf16 因为是双字节

**Comment by Jackarain** [comment]
搞笑的是你吧? 从哪学来的断章取义, 看文章不看上下文?

**Comment by longlongvip** [comment]
> 搞笑的是你吧? 从哪学来的断章取义, 看文章不看上下文?

UTF-16是双字节或四字节，它能表示全部的Unicode字符

**Comment by Jackarain** [comment]
还跑来给我上课呢，除此之外，你还知道什么呢？知道为什么 UTF-16 通常使用 wchar_t 来表示了吗？知道什么叫 Basic Multilingual Plane（BMP）吗？

**Comment by longlongvip** [comment]
> 还跑来给我上课呢，除此之外，你还知道什么呢？知道为什么 UTF-16 通常使用 wchar_t 来表示了吗？知道什么叫 Basic Multilingual Plane（BMP）吗？

[这个](https://142857.red/book/unicode/)讲得好

**Comment by Jackarain** [comment]
莫明其妙
